import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import "./globals.css";
import I18nProvider from "@/components/I18nProvider";
import Header from "@/components/Header";

const manrope = Manrope({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"], // Specify weights you'll use
  variable: "--font-manrope",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` ${manrope.variable} antialiased`}>
        <I18nProvider>
          <Header />
          <div className="md:pt-10">{children}</div>
        </I18nProvider>
      </body>
    </html>
  );
}
